spring:
  datasource:
    url: jdbc:xxx
    username: xx
    password: xx
    type: com.alibaba.druid.pool.DruidDataSource
    #用户名密码，限制访问监控页面
    druid:
      stat-view-servlet:
        login-username: xx
        login-password: xx
logging:
  level:
    root: info
  file:
    path: d:/print/logs/
  pattern:
    console: "%d %thread %logger %msg %n"
server:
  port: 8087
